// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/Angular/04_PravaPristupa/code/blogClient/src/app/login/login.component.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

import { Observable } from 'rxjs/Observable';

import { Router } from '@angular/router';
import { AuthenticationService } from '../services/authentication-service.service';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class LoginComponent implements OnInit {

  public user;

  public wrongUsernameOrPass:boolean;

  constructor(private authenticationService:AuthenticationService,
              private router: Router) {
    this.user = {};
    this.wrongUsernameOrPass = false;
   }

  ngOnInit() {
  }

  login():void{
    this.authenticationService.login(this.user.name, this.user.password).subscribe(
      (loggedIn:boolean) => {
        if(loggedIn){
          this.router.navigate(['/main']);          
        }
      }
    ,
    (err:Error) => {
      if(err.toString()==='Ilegal login'){
        this.wrongUsernameOrPass = true;
        console.log(err);
      }
      else{
        Observable.throw(err);
      }
    });
  }

}

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <form class="form-signin" (ngSubmit)="login()">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="username" class="sr-only">Username</label>
        <input type="text" id="username" class="form-control" name="name" [(ngModel)]="user.name" placeholder="Username"
          required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" name="password" [(ngModel)]="user.password" placeholder="Password"
          required>
        <button class="btn btn-primary btn-block" type="submit">Sign in</button>
      </form>
      <div *ngIf=wrongUsernameOrPass class="alert alert-warning box-msg" role="alert">
        Wrong username or password.
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/React/blog/code/blog-client/src/pages/login/login.component.tsx
import React, { FormEvent } from 'react';

export default class Login extends React.Component<{onLogin: (username:string, password:string)=>void}, {username:string, password:string}> {
    constructor(props:any){
        super(props);
        this.state = {
            username:'',
            password:''
        }
    }
    
    handleSubmit = (event:FormEvent<HTMLFormElement>) => {
        this.props.onLogin(this.state.username, this.state.password);
        event.preventDefault();
    }

    handleChange = (event:{target: {name: any; value:any}}) => {
        const newState = { [event.target.name]: event.target.value } as Pick<{username:string; password:string}, keyof {username: string; password: string}>;
        this.setState(newState);
    }

    render(){
        return (
        <div className="container">
            <div className="row">
                <div className="col-md-3"></div>
                <div className="col-md-6">
                <form className="form-signin" onSubmit={this.handleSubmit}>
                    <h2 className="form-signin-heading">Please sign in</h2>
                    <label htmlFor="username" className="sr-only">Username</label>
                    <input type="text" id="username" className="form-control" name="username" placeholder="Username"
                    required value={this.state.username} onChange={this.handleChange}/>
                    <label htmlFor="inputPassword" className="sr-only">Password</label>
                    <input type="password" id="inputPassword" className="form-control" name="password" placeholder="Password" required value={this.state.password} onChange={this.handleChange}/>
                    <button className="btn btn-primary btn-block" type="submit">Sign in</button>
                </form>
                </div>
                <div className="col-md-3"></div>
            </div>
        </div> 
        )
    }
}
