// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/Angular/03_HTTP/code/primer1/blogClient/src/app/blog-entry-list/blog-entry-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Input } from '@angular/core';
import { BlogEntry } from '../model/blogEntry';
import { Output } from '@angular/core';
import { SharedBlogEntryService } from '../services/shared-blog-entry.service';
import { Router } from '@angular/router';
import { EventEmitter } from '@angular/core';

@Component({
  selector: 'app-blog-entry-list',
  templateUrl: './blog-entry-list.component.html',
  styleUrls: ['./blog-entry-list.component.css']
})
export class BlogEntryListComponent implements OnInit {

  @Input()
  blogEntries:BlogEntry[];

  @Output()
  deleteBlogEntry:EventEmitter<any> = new EventEmitter();

  constructor(private sharedBlogEntryService:SharedBlogEntryService,
              private router:Router) {

  }

  ngOnInit() {
  }

  details(blogEntry:BlogEntry){
    this.router.navigate(['/entry/',blogEntry._id]);
  }

  delete(id:any){
    this.deleteBlogEntry.emit(id);
  }
}

<ul class="list-unstyled">
  <li *ngFor="let blogEntry of blogEntries | async;">
    <app-blog-entry [showComments]="false" [blogEntry]="blogEntry"></app-blog-entry>
    <button class="btn btn-default" (click)="details(blogEntry)">details</button>
    <button class="btn btn-danger" (click)="delete(blogEntry._id)">delete</button>
  </li>
</ul>

// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/React/blog/code/blog-client/src/blog-entry-list/blog-entry-list.component.tsx
import React from 'react';
import BlogEntry from '../blog-entry/blog-entry.component';
import { Link } from 'react-router-dom';

export function BlogEntryList (props: {entries:any[], isLoggedIn:boolean}) {

    const entries = props.entries.map(x =>  
             (<li key={x._id}>
                <BlogEntry entry={x}></BlogEntry>
                { props.isLoggedIn ? <Link to={`/entries/${x._id}`}><button className="btn btn-default">details</button></Link> : null }
                { props.isLoggedIn ? <button className="btn btn-danger">delete</button> : null }
            </li>));
        return (
            <ul className="list-unstyled">
                {entries}
            </ul>
        )
}
