// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/React/blog/code/blog-client/src/blog-entry/blog-entry.component.tsx
import React from 'react';

export default function BlogEntry(props: {entry:any}){
    return (
        <div className="row">
            <div className="col-md-8">
                <h3 className="title"> 
                    {props.entry.title}
                </h3>
                <div>{props.entry.createdAt}</div>
                <div>{props.entry.updatedAt}</div>
                <div className="entry">{props.entry.entry}</div>
                <div>app-coment-list</div>
            </div>
            <div className="col-md-4">
                <div>app-comment-form</div>
            </div>
        </div>
    )
}

// 2 godina/2 god 4 semestar/Klijentske veb tehnologije/Angular/03_HTTP/code/primer1/blogClient/src/app/blog-entry/blog-entry.component.ts
import { Component, OnInit } from '@angular/core';
import { Input } from '@angular/core';
import { BlogEntry } from '../model/blogEntry';

@Component({
  selector: 'app-blog-entry',
  templateUrl: './blog-entry.component.html',
  styleUrls: ['./blog-entry.component.css']
})
export class BlogEntryComponent implements OnInit {

  @Input()
  blogEntry:BlogEntry;

  @Input()
  showComments:boolean;

  constructor() { }

  ngOnInit() {
  }

}

<div class="row">
    <div class="col-md-8" *ngIf="blogEntry" [app-emphasize]="'.title, .entry'" [color]="'#e6ffff'">
        <h3 class="title"> 
            {{blogEntry.title | title}}
        </h3>
        <div *ngIf="blogEntry.createdAt">{{blogEntry.createdAt | date:"dd.MM.yy hh:mm:ss"}}</div>
        <div *ngIf="blogEntry.updatedAt">{{blogEntry.updatedAt | date:"dd.MM.yy hh:mm:ss"}}</div>
        <div class="entry">{{blogEntry.entry}}</div>
        <app-comment-list *ngIf="showComments" [comments]="blogEntry.comments"></app-comment-list>
    </div>
    <div class="col-md-4">
        <app-comment-form (saveComment)="saveComment($event)" *ngIf="showComments"></app-comment-form>
    </div>
</div>
